<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Trip services to Trip change flow test execution in PRP</description>
   <name>SVT_TC_Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2fa32041-f72f-4275-82b7-2bd2a064d31f</testSuiteGuid>
   <testCaseLink>
      <guid>bf8b2409-efd3-4ce9-a458-952f382cba73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Notinuse/Dynamic_TerminalPnr</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d8f046d1-2b46-4b8f-8e54-6ca0ecfafa3a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TerminalData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d8f046d1-2b46-4b8f-8e54-6ca0ecfafa3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SerialNumber</value>
         <variableId>aba54d82-b7f5-43af-992f-d451340f7953</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d8f046d1-2b46-4b8f-8e54-6ca0ecfafa3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Pcc</value>
         <variableId>d710a02e-aae9-49da-b713-5c09c2534e9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d8f046d1-2b46-4b8f-8e54-6ca0ecfafa3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CustomerProfileId</value>
         <variableId>19b5e960-c06b-4391-a8e6-2e6e82223862</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d8f046d1-2b46-4b8f-8e54-6ca0ecfafa3a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>EmptyPnr</value>
         <variableId>f028d891-0d7d-4328-bd8b-10ce60bc7e8a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
